refactor(test): use Node.js native test runner
NodeSecure/i18n pull request #56
Opened 2023-02-16 21:20 UTC by fraxken

Refactor using Node.js native test runner (and cover missing test cases).

Coverage is now at 100%

2023-02-17 13:22 UTC, PierreDemailly requested changes
Everything else lgtm

2023-02-17 13:22 UTC, PierreDemailly commented on test/i18n.js
> +  it("should throw an Error when called with a token that's not a string primitive", async() => {
The test description is wrong
```suggestion
  it("should throw an Error when called with an unknown language", async() => {
```

2023-02-20 16:24 UTC, tony-go approved these changes

2023-02-20 16:24 UTC, tony-go commented
lgtm % ci failure

2023-02-20 18:18 UTC, merged